# Run linting.
#
# Run on python and yaml files.
name: linting
on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pylint and pyyaml
        run: |
          pip install --user pylint pyyaml
      - name: Upgrade pylint-plugin-utils
        run: |
          pip install --upgrade --user git+https://github.com/PyCQA/pylint-plugin-utils.git
      - name: Install pylint_plugin
        run: |
          pip install --user pylint_plugin
      - name: Run pylint on Python files
        run: |
          find . -type f -name "*.py" -print0 | xargs -0 pylint --load-plugins pylint_plugin


