"""Run linting.

Run on .py"""
name: linting
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.9'
      - name: global safe directory 
        run: git config --global --add safe.directory '*'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pylint
        run:  pip install pylint 
      - name: Run pylint on Python files
        run: pylint --jobs=0 $(git ls-files '*.py')
 