# Run linting.
#
# Run on .py
name: linting
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pylint
        run: pip install pylint 
      - name: Run pylint on Python files
        run: pylint --jobs=0 $(git ls-files '*.py')
        