# Run linting.
#
# Run on .py
"""
Github Actions workflow to run pylint on Python files in a repository on every push and pull request.

Triggers:
- Push event on any branch
- Pull request event on any branch

Runs on: 
- Ubuntu latest

Steps:
1. Checkout code
2. Set safe directory for git
3. Upgrade pip
4. Install pylint
5. Run pylint on Python files

Pylint is a Python linter that checks for errors and potential problems in Python code. This workflow installs pylint and runs it on all Python files in the repository, providing feedback on potential issues and suggesting corrections.
"""
name: linting
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: global safe directory 
        run: git config --global --add safe.directory '*'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pylint
        run:  pip install pylint 
      - name: Run pylint on Python files
        run: pylint --jobs=0 $(git ls-files '*.py')
