# Run linting.
#
# Run on python and yaml files.
name: linting
on:
  pull_request
  
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pylint
        run: pip install pylint
      - name: Install PyYAML and PyLint-YAML
        run: pip install PyYAML pylint-yaml
      - name: Run pylint
        run: pylint --load-plugins pylint_yaml **/*.{py, yml}

