# Run linting.
#
# Run on .py.
name: linting
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: global safe directory 
        run: git config --global --add safe.directory '*'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run pylint on Python files
        run: pylint --jobs=0 $(git ls-files '*.py')
 