name: Linting
on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: docker://python:3.10-alpine
        with:
          args: "sh -c 'apk add --update --no-cache gcc musl-dev && pip install -r requirements.txt && flake8 .'"
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
