# Run linting.
#
# Run on python and yaml files.
name: linting
on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pylint and pyyaml
        run: |
          pip install pylint pyyaml
          pip install git+https://github.com/PyCQA/pylint-plugin-utils.git
      - name: Run pylint on Python files
        run: pylint --load-plugins pylint_plugin '**/*.py'